app_service_name       = "Project3-WebApp"
location               = "East US"
resource_group_name    = "PROJECT3"
app_service_plan_name  = "ASP-PROJECT3-8a65"
app_service_plan_id    = "YOUR_APP_SERVICE_PLAN_ID"
