client_id        = "${ARM_CLIENT_ID}"
client_secret    = "${ARM_CLIENT_SECRET}"
subscription_id  = "${ARM_SUBSCRIPTION_ID}"
tenant_id        = "${ARM_TENANT_ID}"
resource_group_name = "Terraform-Porject"
location = "East Us"
app_service_name = "Terraform-PJT"
app_service_plan_name = "PJT3"
